# Generated by Django 5.2.5 on 2025-08-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('book', models.CharField(max_length=50, verbose_name='book')),
                ('text', models.TextField(verbose_name='text')),
                ('likes', models.PositiveIntegerField(verbose_name='likes')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('text', 'author'), name='unique_text_author')],
            },
        ),
    ]
